#!/usr/bin/php
<?php

$sapi = strtolower(php_sapi_name());
if ( 'cli' != $sapi ) {
	g2c_exit('Please run git2cl from the command line');
}

if ( 1 == $argc ) {
	$gitPath = '.';
} else {
	$gitPath = $argv[1];
}

$gitPathEscaped = escapeshellarg($gitPath);
$gitLog = shell_exec("cd {$gitPathEscaped}; git log --date=short --format=%an%n%ae%n%ai%n%s%n###");
$gitLogBits = explode('###' . PHP_EOL, $gitLog);

$gitRealPath = realpath($gitPath);
$changeLogPath = "{$gitRealPath}/ChangeLog";

$fh = fopen($changeLogPath, 'w+');
if ( !$fh ) {
	g2c_exit('Failed to open ./ChangeLog');
}

$changeLog = array();

foreach ( $gitLogBits as $log ) {
	$log = trim($log);
	$bits = explode(PHP_EOL, $log);
	
	if ( count($bits) > 1 ) {
		$author = $bits[0];
		$email = $bits[1];
		$date = $bits[2];
		$message = $bits[3];
		
		$exactDate = date('Y-m-d H:i', strtotime($date));
		$changeLog[$exactDate][] = array(
			'seconds' => date('s', strtotime($date)),
			'author' => $author,
			'email' => $email,
			'message' => $message
		);
	}
}

reset($changeLog);

foreach ( $changeLog as $entryDate => $entryList ) {
	fwrite($fh, $entryDate . PHP_EOL);
	
	foreach ( $entryList as $entry ) {
		fwrite($fh, "\t* {$entry['author']} <{$entry['email']}> {$entry['message']} (+{$entry['seconds']} seconds)" . PHP_EOL);
	}
	
	fwrite($fh, PHP_EOL);
}

fclose($fh);

function g2c_exit($message) {
	echo $message, PHP_EOL;
	exit(0);
}